import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

<<<<<<< HEAD
=======


>>>>>>> main
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

<<<<<<< HEAD
export default function RootLayout({ children }) {
  return (
    <html lang="en">

      
      <body
=======
export default  function RootLayout({ children }) {

  

  return (
    <html lang="en">

      <body
      
>>>>>>> main
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}